Repository yajra/laravel-datatables, pull requests merged in 2018-10, with the labels that each got.

#1860 Added ability to pass an array of needed columns and get only them in response, to not add or remove them one by one
  src/DataTableAbstract.php
  src/Processors/DataProcessor.php
Labels: Hacktoberfest, need docs, need tests

#1811 DATATABLES_ERROR shouldn't be by default null #1805
  src/DataTableAbstract.php
Labels: Hacktoberfest

#1882 [BC] Fix the default name of index column to follow DT syntax.
  src/CollectionDataTable.php
  src/Processors/DataProcessor.php
  src/config/datatables.php
  tests/Integration/QueryEngineTest.php
Labels: Hacktoberfest, bug
